defaults:
  output_dir: C:/Users/JSJ/JSJ AI/JSJ-DOC-ENGINE/03_OUTPUT
  reference_doc: C:/Users/JSJ/JSJ AI/JSJ-DOC-ENGINE/02_TEMPLATES/JSJ-CTE-reference.docx
  templates_dir: C:/Users/JSJ/JSJ AI/JSJ-DOC-ENGINE/02_TEMPLATES
last_project: cte
projects:
- estrutura: C:\Users\JSJ\JSJ AI\CTE\CTE-TEMPLATE-CLAUDE\estrutura.yaml
  id: cte
  mapeamento: C:\Users\JSJ\JSJ AI\CTE\CTE-TEMPLATE-CLAUDE\mapeamento.yaml